# Generated by Django 6.0.4 on 2026-04-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='carbs_per_serving',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Net carbs in grams.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='fiber',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fiber in grams.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='glycemic_index',
            field=models.CharField(blank=True, help_text='Level: Low, Medium, or High.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('RECIPE', 'Recipe'), ('DISCOVERY', 'Discovery')], default='DISCOVERY', help_text="Select 'Recipe' for nutritional content or 'Discovery' for medical breakthroughs.", max_length=10),
        ),
    ]
