# Generated by Django 6.0.4 on 2026-04-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_carbs_per_serving_post_fiber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='net_carbs',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='carbs_per_serving',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='fiber',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='glycemic_index',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('RECIPE', 'Recipe'), ('DISCOVERY', 'Discovery')], default='DISCOVERY', max_length=10),
        ),
    ]
